# Hands On Data Preprocessing

## Numpy Revision

In [2]:
import numpy as np

In [2]:
# creating a python list
my_list = [1,2,3]
print(my_list)

# creating a numpy array
arr = np.array(my_list)
print(arr)

[1, 2, 3]
[1 2 3]


In [3]:
# checking the data type 
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
# creating a python list of lists
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
print(my_matrix)
print(type(my_matrix))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [8]:
# creating a numpy matrix using a python list of lists
np_matrix = np.array(my_matrix)
print(np_matrix)
print(type(np_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [9]:
# array generation
gen_arr = np.arange(0,10)
gen_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
gen_arr2 = np.arange(0,11,2)
gen_arr2

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# array generation using zeros and ones
gen_zero = np.zeros(4)
gen_zero

array([0., 0., 0., 0.])

In [14]:
gen_zero2 = np.zeros([5,5])
gen_zero2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
gen_ones = np.ones(1)
gen_ones

array([1.])

In [16]:
gen_ones2 = np.ones([5,5])
gen_ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# linspace
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
# generating an identity matrix using .eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# generating random number arrays in numpy
np.random.rand(2)

array([0.5853422 , 0.38077549])

In [22]:
np.random.rand(5,5)

array([[0.26141482, 0.58973999, 0.39692391, 0.18847621, 0.55752386],
       [0.34000097, 0.42565288, 0.1852405 , 0.39387666, 0.85255288],
       [0.79216335, 0.49823883, 0.76450008, 0.15758512, 0.79332721],
       [0.14140828, 0.99428435, 0.00634281, 0.44654429, 0.57930969],
       [0.93059611, 0.40094671, 0.99871264, 0.8649944 , 0.3242277 ]])

In [23]:
np.random.randn(3)

array([2.95535435, 1.62641232, 0.0209983 ])

In [24]:
np.random.randn(5,5)

array([[ 1.28732639,  0.28333236, -0.22836689,  0.1650487 ,  0.14011031],
       [ 0.68233978, -0.32986263, -0.50830286,  0.74093286,  0.39383919],
       [-1.64866001,  0.59672352,  0.70113818,  0.54478999,  0.74680499],
       [-0.09822666, -1.96240158,  0.13028013,  0.89489004, -0.41621508],
       [-2.22992841,  0.63556428,  0.04722725,  0.18812351, -1.13854084]])

In [25]:
np.random.randint(0,100)

63

In [26]:
np.random.randint(0,100,10)

array([44, 26,  5, 82, 61, 79, 69, 69, 42, 73])

In [27]:
# array attributes and methods
arr = np.arange(25)
ranarr = np.random.randint(0,50,25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr

array([27, 24, 37, 11, 12, 42, 34,  4, 15, 12,  9, 38, 24, 21, 18,  5, 39,
       11, 16, 26, 10, 29, 31, 14, 17])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

42

In [33]:
ranarr.argmax()

5

In [34]:
ranarr.min()

4

In [35]:
ranarr.argmin()

7

In [36]:
arr.shape

(25,)

In [39]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
arr.reshape(1, 25).shape

(1, 25)

In [41]:
ranarr.dtype

dtype('int64')

In [3]:
# indexing a 2d array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [7]:
#fancy indexing
arr_2dd = np.zeros([10,10])
arr_len = arr_2dd.shape[1]
for i in range(arr_len):
    arr_2dd[i] = i
arr_2dd

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [8]:
arr_2dd[[2,3,4,5]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [10]:
# selection
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [12]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [13]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])